import { ipAddress } from "@vercel/functions";
import { auth, type UserType } from "@/app/(auth)/auth";
import { entitlementsByUserType } from "@/lib/ai/entitlements";
import {
  getChatById,
  getMessageCountByUserId,
  saveChat,
  saveMessages,
  updateChatTitleById,
} from "@/lib/db/queries";
import { ChatbotError } from "@/lib/errors";
import { checkIpRateLimit } from "@/lib/ratelimit";
import { generateTitleFromUserMessage } from "../../../actions";
import { localRequestBodySchema } from "./schema";

/**
 * Persists an exchange generated by an on-device model. `/api/chat` cannot do
 * this because the stream never reaches the server; the client posts the pair
 * of messages once generation finishes.
 */
export async function POST(request: Request) {
  let body: unknown;

  try {
    body = await request.json();
  } catch {
    return new ChatbotError("bad_request:api").toResponse();
  }

  const parsed = localRequestBodySchema.safeParse(body);

  if (!parsed.success) {
    return new ChatbotError("bad_request:api").toResponse();
  }

  const { id, message, assistantMessage, selectedVisibilityType } = parsed.data;

  const session = await auth();

  if (!session?.user) {
    return new ChatbotError("unauthorized:chat").toResponse();
  }

  await checkIpRateLimit(ipAddress(request));

  const userType: UserType = session.user.type;
  const messageCount = await getMessageCountByUserId({
    differenceInHours: 1,
    id: session.user.id,
  });

  if (messageCount > entitlementsByUserType[userType].maxMessagesPerHour) {
    return new ChatbotError("rate_limit:chat").toResponse();
  }

  const chat = await getChatById({ id });

  if (chat && chat.userId !== session.user.id) {
    return new ChatbotError("forbidden:chat").toResponse();
  }

  if (!chat) {
    await saveChat({
      id,
      title: "New chat",
      userId: session.user.id,
      visibility: selectedVisibilityType,
    });

    const title = await generateTitleFromUserMessage({ message });
    await updateChatTitleById({ chatId: id, title });
  }

  await saveMessages({
    messages: [message, assistantMessage].map((item) => ({
      attachments: [],
      chatId: id,
      createdAt: new Date(),
      id: item.id,
      parts: item.parts,
      role: item.role,
    })),
  });

  return Response.json({ status: "ok" });
}
